pt-BR:
  # formatos de data e hora
  date:
    formats:
      default: "%d/%m/%Y"
      short: "%d de %B"
      long: "%d de %B de %Y"
      only_day: "%d"

    day_names: [Domingo, Segunda, Terça, Quarta, Quinta, Sexta, Sábado]
    abbr_day_names: [Dom, Seg, Ter, Qua, Qui, Sex, Sáb]
    month_names: [~, Janeiro, Fevereiro, Março, Abril, Maio, Junho, Julho, Agosto, Setembro, Outubro, Novembro, Dezembro]
    abbr_month_names: [~, Jan, Fev, Mar, Abr, Mai, Jun, Jul, Ago, Set, Out, Nov, Dez]
    order: [:day,:month,:year]

  time:
    formats:
      default: "%A, %d de %B de %Y, %H:%M hs"
      time: "%H:%M hs"
      short: "%d/%m, %H:%M hs"
      long: "%A, %d de %B de %Y, %H:%M hs"
      only_second: "%S"
      datetime:
        formats:
          default: "%Y-%m-%dT%H:%M:%S%Z"
    am: ''
    pm: ''

  # date helper distanci em palavras
  datetime:
    distance_in_words:
      half_a_minute: 'meio minuto'
      less_than_x_seconds:
        one: 'menos de 1 segundo'
        other: 'menos de count segundos'

      x_seconds:
        one: '1 segundo'
        other: 'count segundos'

      less_than_x_minutes:
        one: 'menos de um minuto'
        other: 'menos de count minutos'

      x_minutes:
        one: '1 minuto'
        other: 'count minutos'

      about_x_hours:
        one: 'aproximadamente 1 hora'
        other: 'aproximadamente count horas'

      x_days:
        one: '1 dia'
        other: 'count dias'

      about_x_months:
        one: 'aproximadamente 1 mês'
        other: 'aproximadamente count meses'

      x_months:
        one: '1 mês'
        other: 'count meses'

      about_x_years:
        one: 'aproximadamente 1 ano'
        other: 'aproximadamente count anos'

      over_x_years:
        one: 'mais de 1 ano'
        other: 'mais de count anos'

  # numeros
  number:
    format:
      precision: 3
      separator: ','
      delimiter: '.'
    currency:
      format:
        unit: 'R$'
        precision: 2
        format: '%u %n'
        separator: ','
        delimiter: '.'
    percentage:
      format:
        delimiter: '.'
    precision:
      format:
        delimiter: '.'
    human:
      format:
        precision: 1
        delimiter: '.'
  support:
    array:
      sentence_connector: "e"
      skip_last_comma: true

  # Active Record
  activerecord:
    errors:
      template:
        header:
          one: "Não foi possível gravar {{model}}: 1 erro"
          other: "Não foi possível gravar {{model}}: {{count}} erros"
        body: "Por favor, verifique os seguintes campos:"

      messages:
        inclusion: "não está incluído na lista"
        exclusion: "não está disponível"
        invalid: "não é válido"
        confirmation: "não está de acordo com a confirmação"
        accepted: "precisa de ser aceite"
        empty: "não pode estar vazio"
        blank: "não pode estar vazio"
        too_long: "é muito longo (não mais do que {{count}} caracteres)"
        too_short: "é muito curto (não menos do que {{count}} caracteres)"
        wrong_length: "não é do tamanho correto (precisa ter {{count}} caracteres)"
        taken: "não está disponível"
        not_a_number: "não é um número"
        greater_than: "precisa ser maior do que {{count}}"
        greater_than_or_equal_to: "precisa ser maior ou igual a {{count}}"
        equal_to: "precisa ser igual a {{count}}"
        less_than: "precisa ser menor do que {{count}}"
        less_than_or_equal_to: "precisa ser menor ou igual a {{count}}"
        odd: "precisa ser ímpar"
        even: "precisa ser par"

    # models:
    #   product:
    #     one: "Produto"
    #     other: "Produtos"
    #   product_category:
    #     one: "Categoria de Produto"
    #     other: "Categorias de Produtos"
    #   product_image:
    #     one: "Imagem"
    #     other: "Imagem"
    #   post:
    #     one: "Notícia"
    #     other: "Notícias"
    #   post_image:
    #     one: "Imagem"
    #     other: "Imagem"
    #
    # attributes:
    #   product:
    #     name: "Produto"
    #     price: "Preço"
    #     product_images: "Imagens"
    #     promotional_price: "Preço Promocional"
    #     short_description: "Breve Descrição"
    #     description: "Descrição"
    #   product_category:
    #     name: "Categoria"
    #   product_image:
    #     image_file_name: "Arquivo da imagem"
    #     image_content_type: "Conteúdo do arquivo"
    #     image_file_size: "Tamanho do arquivo"
    #     image_updated_at: "Arquivo atualizado em"
    #   post:
    #     author: "Autor"
    #     title: "Título"
    #     body: "Conteúdo"
    #     created_at: "Criado em"
    #     updated_at: "Atualizado em"
    #   post_image:
    #     image_file_name: "Arquivo da imagem"
    #     image_content_type: "Conteúdo do arquivo"
    #     image_file_size: "Tamanho do arquivo"
    #     image_updated_at: "Arquivo atualizado em"
  pagination:
    next: "próximo"
    previous: "anterior"